language: php

php:
    - 5.6
    - 7.0

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    - SYMFONY_VERSION=~2.8.41

matrix:
    include:
        - php: 7.0
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.0
          env: DEPS=dev SYMFONY_VERSION=~3.1
        - php: 7.0
          env: DEPS=dev COMPOSER_FLAGS="--prefer-stable" SYMFONY_VERSION=~3.1
    fast_finish: true

before_install:
    - echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo 'date.timezone = "Europe/Berlin"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - phpenv config-rm xdebug.ini || true
    - composer self-update
    - if [ "$DEPS" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi

install:
    - composer update --prefer-dist $COMPOSER_FLAGS

before_script:
    - mysql -e 'CREATE DATABASE doctrine_entity_override_test'
    - > 
        echo 'parameters:
            database_driver:   pdo_mysql
            database_host:     127.0.0.1
            database_port:     null
            database_name:     doctrine_entity_override_test
            database_user:     root
            database_password: ~
            locale:            en
       
        ' > ./Tests/Functional/app/config/parameters.yml
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev --prefer-dist
    - php ./Tests/Functional/app/console doctrine:schema:create
    - php ./Tests/Functional/app/console doctrine:schema:update --force

script:
    - 'php ./vendor/bin/phpunit -c ./ --testdox'

after_script:
    - mysql -e 'DROP DATABASE doctrine_entity_override_test;'

notifications:
    email: 127.joschi@gmail.com
